---
- hosts: ansible1.example.com
  gather_facts: no
  tasks:
    - name: Create custom fact on ansible1
      blockinfile:
        path: /etc/ansible/facts.d/local.fact
        create: true
        block: |
          [localfacts]
          type: production
- hosts: ansible2.example.com
  gather_facts: no
  tasks:
    - name: Create custom fact on ansible2
      blockinfile:
        path: /etc/ansible/facts.d/local.fact
        create: true
        block: |
          [localfacts]
          type: testing

