---
- name: create remote management user
  hosts: ansible2
  tasks:
  - name: create user ansible
    user:
      name: ansible
  - name: give them sudo privileges
    lineinfile:
      path: /etc/sudoers.d/ansible
      state: present
      create: true
      mode: 0440
      line: 'ansible ALL=(ALL) NOPASSWD: ALL'
      validate: /usr/sbin/visudo -cf %s
  - debug:
      msg: the remote management user is now created and has sudo privileges

- name: manage user keys
  hosts: localhost
  become: true
  tasks:
  - name: create a directory to store the file that authorized_keys is going to distribute
    file:
      name: ansiblekey
      state: directory
    delegate_to: localhost
  - name: copy the local user ansible ssh key to this directory
    shell: 'cat /home/ansible/.ssh/id_rsa.pub > ansiblekey/id_rsa.pub'
  - debug:
      msg: the local management user key is now in a place where it can be used


- name: create another remote user with a key
  hosts: ansible2
  tasks:
  - name: copy the management user authorized key to the management host
    authorized_key:
      user: ansible
      key: "{{ lookup('file', './ansiblekey/id_rsa.pub') }}"
  - name: create a remote user with an SSH key pair
    user:
      name: anna
      generate_ssh_key: true
      ssh_key_bits: 2048
      ssh_key_file: .ssh/ansiblekey_rsa

