---
- name: test debug verbosity
  hosts: localhost
  become: false
  vars:
    showthis: this only shows when using -vv
  tasks:
  - name: showing verbosity
    debug:
      var: showthis
      verbosity: 2
