  - name: install {{ package }}
    yum:
      name: "{{ package }}"
      state: latest
  - name: start {{ service }}
    service:
      name: "{{ service }}"
      enabled: true
      state: started
